name: module3_task1

# Controls when the workflow will run
on:
  push:
    paths:
      - 'module3_task0/**'
  schedule:
    - cron: '0 0 * * *'

# Jobs has two steps, clone the repo and execute 'make help'
jobs:
  build:
    runs-on: Ubuntu 22.04

    steps:
      - name: clone the repository
        uses: actions/checkout@v3

      - name: Execute the make help command
        run: |
          cd module3_task1/
          make build
