name: module3_task1

# Controls when the workflow will run
on:
  push:
    paths:
      - 'module3_task1/**'
  schedule:
    - cron: '0 0 * * *'

# Jobs has two steps, clone the repo and execute 'make build'
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: clone the repository
        uses: actions/checkout@v3

      - name: Execute the script setup.sh
        run: |
          cd module3_task1/
          ./setup.sh

      - name: Build the application
        run: |
          cd module3_task1/
          make build
